### ISSUE TITLE
Error: Cannot find module 'mkdirp'

### ISSUE THREAD

**Issue by antonkluev** [remotium/cordova-plugin-webrtc#11]
```
cordova plugin add cordova-plugin-webrtc
Installing "cordova-plugin-webrtc" for ios
Failed to install 'cordova-plugin-webrtc': Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/antonkluev/Desktop/Dev/web/uni/mis/presentator/client/plugins/cordova-plugin-webrtc/scripts/pull_webrtc_library.js:13:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
Error: Cannot find module 'mkdirp'
```

**Comment by 1hella** [comment]
I am also having this error

**Comment by qwe9527** [comment]
npm install mkdirp@latest
